[package]
name = "png"
version = "0.4.2"
license = "MIT/Apache-2.0"
description = "PNG decoding library"
authors = ["nwin <nwin@users.noreply.github.com>"]
repository = "https://github.com/PistonDevelopers/image-png.git"
exclude = [
    "tests/*",
]

[dependencies]
#inflate = "0.1.0"
inflate = { path = "../inflate" }
flate2 = { version = "0.2.11", optional = true }
libc = "0.2.1"
num = "0.1.27"
bitflags = "0.3.2"

[dev-dependencies]
getopts = "0.2.14"
term = "0.2"
glob = "0.2.11"

[dev-dependencies.glium]
version = "0.13.5"
features = ["glutin"]
default-features = false

[features]
png-encoding = ["flate2"]
default = ["png-encoding"]
unstable = []
